### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/patrol#173]
This issue tracks documentation-related efforts.

- [x] #196
- [x] #81
- [x] #205 
- [x] #284
- [x] #285
- [ ] add docs for global configuration using `PatrolTesterConfig`
- [ ] add some examples for the`patrol drive` CLI command
  - [ ] say that files must end with `_test.dart` to be run by Patrol
- [ ] explain how `RichText` are different and how work with them
- [ ] add more documentation about how Patrol's custom finders are working
  - why `.first`, `.last`, `.,at()` may cause problems
- [x] say about 2 ways of initializing `NativeAutomator`:
- [ ] #286 
- [ ] #287 
- [x] #299
- [ ] #333
- [ ] Write that we optimize for 90% of use cases and strive to stay consistent with Flutter, but improve for tester/developer experience where possible.
- [ ] Patrol's native automation is a novel feature in the Flutter world, and you might be curious about how we built it. We should document the architecture and internals (requested [here](https://github.com/leancodepl/patrol/issues/332#issuecomment-1278539448))

**Comment by bartekpacia** [comment]
Thanks a lot for sharing this with us @lmlikota! :D 

This sounds like a good candidate to add to the Tips & Tricks section in the docs. You can create a PR if you feel like if. If not, I'll do it in the near future.

**Comment by lmlikota** [comment]
I will create PR later in the evening. I'm glad I can help a bit 🙂

**Comment by bartekpacia** [comment]
We've made a lot of progress in terms of documentation, and I think it's a good time to close this issue :)

Please open new issues if you spot some bug or have a feature request regarding our docs.
