### ISSUE TITLE
[Meta] - Support for deep link tests

### ISSUE THREAD

**Issue by matthew-carroll** [leancodepl/patrol#2457]
This is a meta ticket, which covers multiple related asks for deep link tests.

- [ ] Documentation - Guide(s) for the current approach to testing deep links with Patrol
- [ ] All lifecycles - Deep links can arrive at three different times. Each code path is different, and therefore each code path can have its own bugs. I'd like to test all three:
    - [ ] Cold boot (app is not in memory)
    - [ ] Background (app is in memory, but not executing code)
    - [ ] Foreground (app is visible on screen)

Deep links can be critical for business concerns. For example, a deep link might be used to get to a sign up page, or to a purchase page. Errors in such deep link handling can lead users to leave.

Moreover, deep links happen to be behaviors that aren't tested in the natural development process. Most developers don't even know how to simulate a deep link, let alone do it on a regular basis. Therefore, deep links are a perfect candidate for automated tests.

**Comment by bartekpacia** [comment]
Linking past discussion in #556

**Comment by Kendru98** [comment]
Hi, Patrol already support testing deeplinks, but we should add docs page for it. You can use $.native.openUrl()
